name: Изменение репозитория
description: Задача на структурные изменения, шаблоны и организацию репозитория
title: '[Feature] '
type: Feature
projects: ['Phoenix-Games-Revolution/1']
body:
  - type: textarea
    id: context
    attributes:
      label: С чем связан запрос
      description: Опиши, зачем нужен этот набор изменений и какую проблему он закрывает
    validations:
      required: true

  - type: textarea
    id: plan
    attributes:
      label: План изменений
      description: Перечисли, что именно должно быть изменено в репозитории
    validations:
      required: true

  - type: textarea
    id: done
    attributes:
      label: Критерии готовности
      description: Зафиксируй, по каким признакам задача считается завершённой
    validations:
      required: true
