name: Технология эпохи
description: Задача на описание технологии конкретного этапа эпохи
title: "[Технология] Название технологии"
type: Technology
projects: ['Phoenix-Games-Revolution/7']
body:
  - type: dropdown
    id: epoch-stage
    attributes:
      label: Этап эпохи
      description: Выбери этап, к которому относится технология
      options:
        - Палеолит
        - Мезолит
        - Неолит
        - Энеолит
        - Бронзовый век
        - Ранний железный век
    validations:
      required: true

  - type: dropdown
    id: technology-category
    attributes:
      label: Категория технологии
      description: Укажи, к какой категории относится технология
      options:
        - Военная
        - Экономическая
        - Социальная
        - Производственная
        - Научная
        - Ритуальная
    validations:
      required: true

  - type: textarea
    id: short-description
    attributes:
      label: Краткое описание технологии
      description: Коротко, без деталей, опиши суть технологии
      placeholder: "Одним предложением, что делает или улучшает технология."
    validations:
      required: true
